[tilletia]
agb-ai01 ansible_host=10.23.56.101
kve-ai01 ansible_host=10.24.56.101
rde-ai01 ansible_host=10.25.56.101
zhe-ai01 ansible_host=10.28.56.101
dbe-ai01 ansible_host=10.34.56.101
pde-ai01 ansible_host=10.33.56.101
dze-ai01 ansible_host=10.27.56.101
srm-ai01 ansible_host=10.36.56.101
vlm-ai01 ansible_host=10.35.56.101

[tilletia:vars]
ansible_user=s-lab-ai
ansible_python_interpreter=/usr/bin/python3
repo_url=https://github.com/Agroprosperis/jetson-webapp.git
install_dir=/opt/tilletia-app
expected_ubuntu_version=24.04
expected_ubuntu_codename=noble
